from __future__ import annotations

from haoyue_optimizer.core.models import Optimization
from haoyue_optimizer.core.registry import RegistrySetAction
from haoyue_optimizer.core.scheduled_task import ScheduledTaskSetEnabledAction
from haoyue_optimizer.core.subprocess_action import SubprocessAction


def get_optimizations() -> list[Optimization]:
    return [
        Optimization(
            id="disable_basic_telemetry",
            title="禁用基础遥测和广告 ID",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["减少诊断和个性化广告数据收集"],
            side_effects=["Windows 个性化推荐和反馈体验减少"],
            legacy_ids=["telemetry", "tracking"],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "AllowTelemetry", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\SQMClient\Windows", "CEIPEnable", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo", "Enabled", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_content_delivery",
            title="禁用推荐内容和 Windows 技巧",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["减少开始菜单、锁屏和系统提示中的推荐内容"],
            side_effects=["Windows 新功能提示和个性化内容减少"],
            legacy_ids=["content_del", "feeds"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SystemPaneSuggestionsEnabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SoftLandingEnabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "RotatingLockScreenEnabled", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_telemetry_ex",
            title="禁用扩展遥测和反馈数据收集",
            category="privacy",
            preset="aggressive",
            risk="green",
            evidence="medium",
            benefit=["减少 Connected User Experiences、反馈通知和语音数据上传"],
            side_effects=["语音识别、墨迹输入个性化和反馈中心功能受限"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "LimitDiagnosticLogWriter", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "LimitDumpCollection", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection", "AllowTelemetry", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 1, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\InputPersonalization", "RestrictImplicitTextCollection", 1, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy", "HasAccepted", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_disable_bg_tasks",
            title="禁用诊断和系统维护计划任务",
            category="privacy",
            preset="aggressive",
            risk="green",
            evidence="medium",
            benefit=["减少磁盘诊断、内存诊断、碎片整理和 Windows 错误报告后台任务"],
            side_effects=["磁盘健康告警不再自动触发，错误报告队列不再自动上传，碎片整理不再自动运行"],
            legacy_ids=["disable_bg_tasks"],
            actions=[
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector", enabled=False),
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\MemoryDiagnostic\ProcessMemoryDiagnosticEvents", enabled=False),
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\Windows Error Reporting\QueueReporting", enabled=False),
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\Defrag\ScheduledDefrag", enabled=False),
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\MemoryDiagnostic\RunFullMemoryDiagnostic", enabled=False),
                ScheduledTaskSetEnabledAction(r"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip", enabled=False),
            ],
        ),
        Optimization(
            id="disable_delivery_optimization",
            title="禁用交付优化 (P2P 更新分发)",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止 Windows 使用 P2P 分发更新，减少后台网络上传"],
            side_effects=["更新下载不再利用局域网 P2P 加速，全量从微软服务器下载"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization", "DODownloadMode", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_app_compat_telemetry",
            title="禁用应用程序兼容性遥测",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["禁用兼容性遥测引擎、程序兼容性助手和应用影响遥测"],
            side_effects=["旧程序兼容性提示不再显示，兼容性数据不再收集"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "AITEnable", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "DisableEngine", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "DisablePCA", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "DisableUAR", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_license_telemetry",
            title="禁用许可遥测",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 生成许可验证遥测票据"],
            side_effects=["许可验证遥测不再生成"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform", "NoGenTicket", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_dotnet_telemetry",
            title="禁用 .NET CLI 遥测",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止 .NET CLI 工具发送使用数据遥测"],
            side_effects=["无实际副作用"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"Environment", "DOTNET_CLI_TELEMETRY_OPTOUT", "1", "sz"),
            ],
        ),
        Optimization(
            id="disable_edge_boost",
            title="禁用 Edge 后台预启动",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止 Edge 浏览器在后台预启动和关闭后继续运行"],
            side_effects=["Edge 启动速度略慢，不会在后台占用资源"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "StartupBoostEnabled", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "AllowPrelaunch", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "BackgroundModeEnabled", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_webcam_telemetry",
            title="禁用网络摄像头遥测",
            category="privacy",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["阻止系统级摄像头访问数据收集"],
            side_effects=["系统级摄像头访问策略设为拒绝，部分应用摄像头权限可能受影响"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Deny", "sz"),
            ],
        ),
        Optimization(
            id="disable_cortana",
            title="禁用 Cortana 和云搜索",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["关闭 Cortana 语音助手和云端搜索，减少数据上传"],
            side_effects=["Cortana 不再可用，搜索不包含网络结果"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCloudSearch", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortanaAboveLock", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowSearchToUseLocation", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "ConnectedSearchUseWeb", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Search", "ConnectedSearchUseWebOverMeteredConnections", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_cloud_content",
            title="禁用 Windows 云内容和第三方建议",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止 Windows 推送第三方应用建议和消费功能"],
            side_effects=["开始菜单不再推荐应用和内容"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\CloudContent", "DisableThirdPartySuggestions", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\CloudContent", "DisableWindowsConsumerFeatures", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_credssp_logging",
            title="禁用 CredSSP 调试日志",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["关闭凭据安全支持提供程序的调试日志"],
            side_effects=["CredSSP 调试日志不再记录"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Lsa\Credssp", "DebugLogLevel", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_onedrive",
            title="禁用 OneDrive 文件同步",
            category="privacy",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["阻止 OneDrive 自动同步文件和默认保存到 OneDrive"],
            side_effects=["OneDrive 文件同步不可用，需要手动管理云存储"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\OneDrive", "DisableFileSync", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\OneDrive", "DisableFileSyncNGSC", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_wmi_autologger",
            title="批量禁用 WMI 事件日志记录器",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用 30 个 WMI Autologger 减少磁盘写入和 CPU 开销"],
            side_effects=["相关 ETW 日志不再记录，排查问题时缺少日志"],
            legacy_ids=[],
            actions=[
                *[RegistrySetAction("HKLM", rf"SYSTEM\CurrentControlSet\Control\WMI\Autologger\{name}", "Start", 0, "dword", qualifier=name[:8])
                  for name in [
                      "AppModel", "Cellcore", "Circular Kernel Context Logger",
                      "CloudExperienceHostOobe", "DataMarket",
                      "DiagLog", "HolographicDevice",
                      "iclsClient", "iclsProxy", "LwtNetLog",
                      "Microsoft-Windows-AssignedAccess-Trace", "Microsoft-Windows-Setup",
                      "NBSMBLOGGER", "PEAuthLog", "RdrLog", "ReadyBoot",
                      "SetupPlatform", "SetupPlatformTel", "SocketHeciServer",
                      "SpoolerLogger", "SQMLogger", "TCPIPLOGGER",
                      "TileStore", "Tpm", "TPMProvisioningService",
                      "UBPM", "WdiContextLog", "WFP-IPsec Trace",
                      "WiFiDriverIHVSession", "WiFiDriverIHVSessionRepro",
                      "WiFiSession", "WinPhoneCritical",
                  ]],
            ],
        ),
        Optimization(
            id="disable_activity_history",
            title="禁用活动历史记录和时间线",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 Windows 收集和上传用户活动历史"],
            side_effects=["时间线和活动历史功能不可用"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "EnableActivityFeed", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "PublishUserActivities", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\System", "UploadUserActivities", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_location_tracking",
            title="禁用位置跟踪",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["全局禁用位置服务，阻止应用和系统获取位置信息"],
            side_effects=["天气、地图、查找设备等依赖位置的功能不可用"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors", "DisableLocation", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors", "DisableWindowsLocationProvider", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors", "DisableLocationScripting", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_feedback",
            title="禁用反馈和诊断通知",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 弹出反馈请求和诊断通知"],
            side_effects=["反馈中心不再主动请求反馈"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Siuf\Rules", "PeriodInNanoSeconds", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\DataCollection", "DoNotShowFeedbackNotifications", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_wifi_sense",
            title="禁用 Wi-Fi Sense 和热点推荐",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用自动连接建议热点和 Wi-Fi Sense 共享"],
            side_effects=["Wi-Fi Sense 自动连接和密码共享不可用"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowWiFiHotSpotReporting", "Value", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots", "Value", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config", "AutoConnectAllowedOEM", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_handwriting",
            title="禁用手写数据收集和个性化",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止手写识别数据上传和个性化学习"],
            side_effects=["手写个性化和云端识别改进不可用"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\TabletPC", "PreventHandwritingDataSharing", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppPrivacy", "LetAppsActivateWithVoice", 2, "dword"),
            ],
        ),
        Optimization(
            id="disable_map_updates",
            title="禁用离线地图自动更新",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 地图在后台自动下载更新"],
            side_effects=["离线地图不会自动更新"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Maps", "AutoDownloadAndUpdateMapData", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Maps", "AllowUntriggeredNetworkTrafficOnSettingsPage", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_app_diagnostics",
            title="限制应用诊断数据访问",
            category="privacy",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止应用访问其他应用的诊断数据"],
            side_effects=["需要诊断数据的应用功能可能受限"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics", "Value", "Deny", "sz"),
            ],
        ),
        Optimization(
            id="block_telemetry_firewall",
            title="防火墙阻止遥测服务出站",
            category="privacy",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["通过防火墙出站规则阻止 DiagTrack/WerSvc 数据上传，即使服务被重新启用也无法外发"],
            side_effects=["需要管理员权限，规则可通过 netsh 删除回滚"],
            legacy_ids=[],
            requires_admin=True,
            actions=[
                SubprocessAction(
                    action_id="firewall:block_diagtrack",
                    target="Block DiagTrack outbound",
                    apply_cmd=["netsh", "advfirewall", "firewall", "add", "rule", "name=Block-DiagTrack-Out", "dir=out", "action=block", "service=DiagTrack"],
                    rollback_cmd=["netsh", "advfirewall", "firewall", "delete", "rule", "name=Block-DiagTrack-Out"],
                    verify_cmd=["powershell", "-Command", "if(netsh advfirewall firewall show rule name=Block-DiagTrack-Out 2>$null | Select-String 'Block-DiagTrack-Out'){exit 0}else{exit 1}"],
                ),
                SubprocessAction(
                    action_id="firewall:block_wersvc",
                    target="Block WerSvc outbound",
                    apply_cmd=["netsh", "advfirewall", "firewall", "add", "rule", "name=Block-WerSvc-Out", "dir=out", "action=block", "service=WerSvc"],
                    rollback_cmd=["netsh", "advfirewall", "firewall", "delete", "rule", "name=Block-WerSvc-Out"],
                    verify_cmd=["powershell", "-Command", "if(netsh advfirewall firewall show rule name=Block-WerSvc-Out 2>$null | Select-String 'Block-WerSvc-Out'){exit 0}else{exit 1}"],
                ),
            ],
        ),
    ]
