from __future__ import annotations

from haoyue_optimizer.core.models import Optimization
from haoyue_optimizer.core.registry import RegistrySetAction
from haoyue_optimizer.core.service import ServiceStartTypeAction
from haoyue_optimizer.core.subprocess_action import SubprocessAction


def get_optimizations() -> list[Optimization]:
    return [
        Optimization(
            id="disable_xbl_auth",
            title="禁用 Xbox 认证服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少 Xbox 认证相关后台服务资源占用"],
            side_effects=["Xbox Live 认证不可用，Xbox 联动功能受影响"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("XblAuthManager", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_xbl_gamesave",
            title="禁用 Xbox 存档同步服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少 Xbox 存档同步后台服务资源占用"],
            side_effects=["Xbox 游戏存档云同步不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("XblGameSave", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_xbox_netapi",
            title="禁用 Xbox 网络服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少 Xbox 网络API后台服务资源占用"],
            side_effects=["Xbox 网络功能不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("XboxNetApiSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_maps_broker",
            title="禁用地图下载服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止地图数据后台下载和服务"],
            side_effects=["离线地图功能不可用"],
            legacy_ids=["mapsbroker"],
            actions=[
                ServiceStartTypeAction("MapsBroker", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_diagtrack",
            title="禁用诊断跟踪服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["停止 Connected User Experiences 遥测数据收集"],
            side_effects=["Windows 遥测和诊断数据收集停止"],
            legacy_ids=["svc_safe"],
            actions=[
                ServiceStartTypeAction("DiagTrack", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_remote_registry",
            title="禁用远程注册表服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止远程注册表访问，提升安全性"],
            side_effects=["远程注册表访问不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("RemoteRegistry", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_fax",
            title="禁用传真服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["停止传真服务后台资源占用"],
            side_effects=["传真功能不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("Fax", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_wersvc",
            title="禁用 Windows 错误报告服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止错误报告自动上传"],
            side_effects=["应用崩溃时不再自动生成错误报告"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("WerSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_ucpd",
            title="禁用用户选择保护驱动",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["禁用 UCPD 驱动，解除部分默认应用锁定限制"],
            side_effects=["UCPD 驱动禁用，Windows 默认应用保护机制失效"],
            legacy_ids=[],
            requires_admin=True,
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Services\UCPD", "Start", 4, "dword"),
            ],
        ),
        Optimization(
            id="disable_sensor_services",
            title="禁用传感器监控服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止传感器监控和数据采集服务"],
            side_effects=["传感器相关功能（自动旋转、环境光等）不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("SensrSvc", "disabled", stop=True),
                ServiceStartTypeAction("SensorDataService", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="configure_mmcss",
            title="优化 MMCSS 多媒体调度服务",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["保留 MMCSS 服务但优化 SystemResponsiveness=10，减少多媒体调度对前台的干扰"],
            side_effects=["MMCSS 服务保持运行但参数被修改，多媒体调度策略改变"],
            legacy_ids=["disable_mmcss"],
            requires_admin=True,
            actions=[
                ServiceStartTypeAction("MMCSS", "auto"),
            ],
        ),
        Optimization(
            id="disable_windows_search",
            title="禁用 Windows Search 索引服务",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["停止搜索索引的后台 CPU 和磁盘 I/O 开销"],
            side_effects=["开始菜单搜索变慢，依赖索引的搜索功能不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("WSearch", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="eventlog_demand_start",
            title="Windows Event Log 改为按需启动",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="low",
            benefit=["减少后台事件日志的磁盘写入 I/O"],
            side_effects=["事件日志不再常驻运行，部分依赖实时日志的功能可能受影响"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("EventLog", "manual"),
            ],
        ),
        # ── 批量禁用安全且高频无用的系统服务 ──
        Optimization(
            id="disable_geolocation",
            title="禁用地理位置服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止位置跟踪和传感器数据采集"],
            side_effects=["天气/地图/查找设备等依赖位置的功能不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("lfsvc", "disabled", stop=True),
                ServiceStartTypeAction("GeoSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_phone_services",
            title="禁用手机和蓝牙联动服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 Phone/PhoneSvc/Tethering 后台资源占用"],
            side_effects=["手机连接、蓝牙共享网络等不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("PhoneSvc", "disabled", stop=True),
                ServiceStartTypeAction("TapiSrv", "disabled", stop=True),
                ServiceStartTypeAction("BthHFSrv", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_biometrics",
            title="禁用生物识别服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 Windows Biometric Service 后台资源占用"],
            side_effects=["指纹/面部识别等生物识别登录不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("WbioSrvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_shared_experiences",
            title="禁用跨设备体验服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止跨设备通知/应用接续等后台同步"],
            side_effects=["跨设备剪贴板、通知同步等不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("RmSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_contact_data",
            title="禁用联系人数据和日历同步",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 PimIndexMaintenance/ContactData 后台同步"],
            side_effects=["人脉/日历的 Exchange/Outlook 同步不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("PimIndexMaintenanceSvc", "disabled", stop=True),
                ServiceStartTypeAction("ContactDataSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_diagnostic_services",
            title="禁用诊断相关服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止诊断策略服务、诊断执行服务和设备管理无线事件的日志"],
            side_effects=["Windows 故障诊断和疑难解答不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("DPS", "disabled", stop=True),
                ServiceStartTypeAction("WdiServiceHost", "disabled", stop=True),
                ServiceStartTypeAction("WdiSystemHost", "disabled", stop=True),
                ServiceStartTypeAction("dmwappushservice", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_nfc",
            title="禁用 NFC 服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 NFC 后台服务资源占用"],
            side_effects=["NFC 近场通信功能不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("NfcService", "disabled", stop=True),
                ServiceStartTypeAction("SEMgrSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_print_services",
            title="禁用打印和传真相关服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 Print Spooler/PrintNotify/Fax 后台资源占用"],
            side_effects=["本地和网络打印机不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("Spooler", "disabled", stop=True),
                ServiceStartTypeAction("PrintNotify", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_remote_services",
            title="禁用远程桌面和协助服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止远程桌面、远程协助和远程差分压缩后台资源占用"],
            side_effects=["无法被远程连接，远程协助不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("SessionEnv", "disabled", stop=True),
                ServiceStartTypeAction("RpcLocator", "disabled", stop=True),
                ServiceStartTypeAction("UmRdpService", "disabled", stop=True),
                ServiceStartTypeAction("RasAuto", "disabled", stop=True),
                ServiceStartTypeAction("RasMan", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_smartcard",
            title="禁用智能卡服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止智能卡即插即用和枚举器后台资源占用"],
            side_effects=["智能卡登录和认证不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("SCardSvr", "disabled", stop=True),
                ServiceStartTypeAction("ScDeviceEnum", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_retail_demo",
            title="禁用零售演示服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["停止零售演示模式服务"],
            side_effects=["零售演示模式不可用（普通用户完全不需要）"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("RetailDemo", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_wallet_services",
            title="禁用钱包和支付服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 WalletService/TokenBroker 后台资源占用"],
            side_effects=["Windows 支付和令牌代理不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("WalletService", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_update_orchestrator",
            title="禁用 Windows Update 编排服务",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["停止更新编排和 Medic 服务，阻止后台自动更新调度"],
            side_effects=["Windows Update 自动调度不可用，需手动检查更新"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("UsoSvc", "disabled", stop=True),
                ServiceStartTypeAction("wuauserv", "disabled", stop=True),
                ServiceStartTypeAction("WaaSMedicSvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_windows_insider",
            title="禁用 Windows Insider 服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 Insider 计划相关服务"],
            side_effects=["Windows Insider 预览版更新不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("wisvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_threat_intel",
            title="禁用威胁情报和安全中心推送",
            category="services",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["停止威胁情报收集和安全中心通知推送"],
            side_effects=["安全中心通知和威胁情报不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("wscsvc", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_tablet_input",
            title="禁用平板电脑输入服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止触摸键盘和手写面板服务，桌面用户无需此服务"],
            side_effects=["触摸键盘和手写面板不可用"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("TabletInputService", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_link_tracking",
            title="禁用分布式链接跟踪服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 NTFS 文件移动/重命名跟踪，减少后台 I/O"],
            side_effects=["跨域文件链接跟踪不可用（普通桌面无影响）"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("TrkWks", "disabled", stop=True),
            ],
        ),
        Optimization(
            id="disable_upnp",
            title="禁用 UPnP 设备发现和主机服务",
            category="services",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["停止 SSDP/UPnP 后台设备发现，减少网络广播"],
            side_effects=["UPnP 设备发现不可用，影响部分 NAS/投屏发现"],
            legacy_ids=[],
            actions=[
                ServiceStartTypeAction("SSDPSRV", "disabled", stop=True),
                ServiceStartTypeAction("upnphost", "disabled", stop=True),
            ],
        ),
    ]
