from __future__ import annotations

from haoyue_optimizer.core.models import Optimization
from haoyue_optimizer.core.registry import RegistrySetAction


def get_optimizations() -> list[Optimization]:
    return [
        Optimization(
            id="disable_setting_sync",
            title="禁用 Windows 设置同步",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少跨设备同步带来的后台网络和存储开销"],
            side_effects=["浏览器设置、辅助功能、个性化等不再跨设备同步"],
            legacy_ids=["setting_sync"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync", "SyncPolicy", 5, "dword"),
            ],
        ),
        Optimization(
            id="disable_startup_delay",
            title="禁用启动延迟",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["开机后启动程序立即运行，无需等待系统延迟"],
            side_effects=["更多启动项同时加载可能短暂增加开机磁盘负载"],
            legacy_ids=["startup_delay"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Serialize", "StartupDelayInMSec", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_autorun",
            title="禁用自动运行",
            category="system",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止可移动驱动器自动运行，降低恶意软件自动执行风险"],
            side_effects=["插入 U 盘或光盘时不再自动弹出操作选择窗口"],
            legacy_ids=["autorun"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoDriveTypeAutoRun", 0xFF, "dword"),
            ],
        ),
        Optimization(
            id="disable_explorer_restart",
            title="禁止 Explorer 崩溃后自动重启",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["Explorer 崩溃后保持关闭，便于排查问题或避免循环重启"],
            side_effects=["Explorer 崩溃后需手动重新启动桌面和任务栏"],
            legacy_ids=["explorer_restart"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\NT\CurrentVersion\Winlogon", "AutoRestartShell", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_map_download",
            title="禁用地图数据下载",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 地图在后台下载离线数据，减少网络和存储开销"],
            side_effects=["离线地图功能不可用，地图应用需要联网才能使用"],
            legacy_ids=["map_download"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Maps", "DownloadOverMeteredConnection", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_svchost_thresh",
            title="调整 svchost 拆分阈值",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["优化 svchost 进程拆分阈值，减少进程数量"],
            side_effects=["svchost 进程拆分阈值改变，内存使用模式可能变化"],
            legacy_ids=["svchost_thresh"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\ControlSet001\Control", "SvcHostSplitThresholdInKB", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_file_alloc",
            title="优化文件分配单元大小",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["调整文件分配单元大小以优化存储性能"],
            side_effects=["文件分配单元大小调整"],
            legacy_ids=["file_alloc"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "ConfigFileAllocSize", 500, "dword"),
            ],
        ),
        Optimization(
            id="disable_admin_share",
            title="禁用管理共享",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用 C$、D$、ADMIN$ 等默认管理共享，提升安全性"],
            side_effects=["管理共享（C$, D$, ADMIN$）被禁用，远程管理可能受影响"],
            legacy_ids=["admin_share"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "AutoShareServer", 0, "dword"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "AutoShareWks", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_background_apps",
            title="禁用后台应用",
            category="system",
            preset="aggressive",
            risk="green",
            evidence="high",
            benefit=["减少后台应用资源占用"],
            side_effects=["后台应用全局禁用，通知和 Live Tile 更新可能受影响"],
            legacy_ids=["bg_apps"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications", "GlobalUserDisabled", 1, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search", "BackgroundAppGlobalToggle", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_driver_search",
            title="禁用驱动自动搜索",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["阻止 Windows Update 自动搜索和安装驱动"],
            side_effects=["Windows Update 不再自动搜索驱动，需手动安装驱动"],
            legacy_ids=["driver_search"],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching", "SearchOrderConfig", 0, "dword"),
            ],
        ),
        Optimization(
            id="extend_wu_pause_limit",
            title="延长 Windows 更新暂停上限",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["允许暂停 Windows 更新最长 10 年，仅放宽 UI 限制"],
            side_effects=["允许暂停更新最长 3650 天（10 年），仅放宽 UI 限制"],
            legacy_ids=["wu_pause"],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\UpdateUX\Settings", "FlightSettingsMaxPauseDays", 3650, "dword"),
            ],
        ),
    ]
