from __future__ import annotations

from haoyue_optimizer.core.models import Optimization
from haoyue_optimizer.core.registry import RegistrySetAction


IFEO_BASE = r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options"


def get_optimizations() -> list[Optimization]:
    return [
        Optimization(
            id="disable_setting_sync",
            title="禁用 Windows 设置同步",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少跨设备同步带来的后台网络和存储开销"],
            side_effects=["浏览器设置、辅助功能、个性化等不再跨设备同步"],
            legacy_ids=["setting_sync"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync", "SyncPolicy", 5, "dword"),
            ],
        ),
        Optimization(
            id="disable_startup_delay",
            title="禁用启动延迟",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["开机后启动程序立即运行，无需等待系统延迟"],
            side_effects=["更多启动项同时加载可能短暂增加开机磁盘负载"],
            legacy_ids=["startup_delay"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Serialize", "StartupDelayInMSec", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_autorun",
            title="禁用自动运行",
            category="system",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止可移动驱动器自动运行，降低恶意软件自动执行风险"],
            side_effects=["插入 U 盘或光盘时不再自动弹出操作选择窗口"],
            legacy_ids=["autorun"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoDriveTypeAutoRun", 0xFF, "dword"),
            ],
        ),
        Optimization(
            id="disable_explorer_restart",
            title="禁止 Explorer 崩溃后自动重启",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["Explorer 崩溃后保持关闭，便于排查问题或避免循环重启"],
            side_effects=["Explorer 崩溃后需手动重新启动桌面和任务栏"],
            legacy_ids=["explorer_restart"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\NT\CurrentVersion\Winlogon", "AutoRestartShell", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_map_download",
            title="禁用地图数据下载",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 地图在后台下载离线数据，减少网络和存储开销"],
            side_effects=["离线地图功能不可用，地图应用需要联网才能使用"],
            legacy_ids=["map_download"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Maps", "DownloadOverMeteredConnection", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_svchost_thresh",
            title="调整 svchost 拆分阈值",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["优化 svchost 进程拆分阈值，减少进程数量（仅 extreme 模式）"],
            side_effects=["svchost 进程合并会降低隔离性和排错性，普通模式不建议执行"],
            legacy_ids=["svchost_thresh"],
            applicability=["extreme_only"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\ControlSet001\Control", "SvcHostSplitThresholdInKB", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_file_alloc",
            title="优化文件分配单元大小",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["调整文件分配单元大小以优化存储性能"],
            side_effects=["文件分配单元大小调整"],
            legacy_ids=["file_alloc"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\FileSystem", "ConfigFileAllocSize", 500, "dword"),
            ],
        ),
        Optimization(
            id="disable_admin_share",
            title="禁用管理共享",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用 C$、D$、ADMIN$ 等默认管理共享，提升安全性"],
            side_effects=["管理共享（C$, D$, ADMIN$）被禁用，远程管理可能受影响"],
            legacy_ids=["admin_share"],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "AutoShareServer", 0, "dword"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "AutoShareWks", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_background_apps",
            title="禁用后台应用",
            category="system",
            preset="aggressive",
            risk="green",
            evidence="high",
            benefit=["减少后台应用资源占用（不破坏 UWP/Store 基础设施）"],
            side_effects=["后台应用全局禁用，通知和 Live Tile 更新可能受影响"],
            legacy_ids=["bg_apps"],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications", "GlobalUserDisabled", 1, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search", "BackgroundAppGlobalToggle", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_driver_search",
            title="禁用驱动自动搜索",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["阻止 Windows Update 自动搜索和安装驱动"],
            side_effects=["Windows Update 不再自动搜索驱动，需手动安装驱动"],
            legacy_ids=["driver_search"],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching", "SearchOrderConfig", 0, "dword"),
            ],
        ),
        Optimization(
            id="extend_wu_pause_limit",
            title="延长 Windows 更新暂停上限",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["允许暂停 Windows 更新最长 10 年，仅放宽 UI 限制"],
            side_effects=["允许暂停更新最长 3650 天（10 年），仅放宽 UI 限制"],
            legacy_ids=["wu_pause"],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\UpdateUX\Settings", "FlightSettingsMaxPauseDays", 3650, "dword"),
            ],
        ),
        Optimization(
            id="shorten_task_timeout",
            title="缩短应用关闭超时",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["缩短无响应应用等待时间，加快关机和应用关闭速度"],
            side_effects=["无响应应用被更快强制关闭，未保存数据可能丢失"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"Control Panel\Desktop", "HungAppTimeout", "1000", "sz"),
                RegistrySetAction("HKCU", r"Control Panel\Desktop", "WaitToKillAppTimeout", "2000", "sz"),
                RegistrySetAction("HKCU", r"Control Panel\Desktop", "LowLevelHooksTimeout", "1000", "sz"),
            ],
        ),
        Optimization(
            id="shorten_service_timeout",
            title="缩短服务关闭超时",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["缩短服务关闭等待时间，加快系统关机速度"],
            side_effects=["服务被更快终止，正在执行的服务任务可能中断"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control", "WaitToKillServiceTimeout", "2000", "sz"),
            ],
        ),
        Optimization(
            id="disable_auto_maintenance",
            title="禁用自动维护",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止 Windows 在空闲时自动执行磁盘优化、安全扫描等维护任务"],
            side_effects=["自动维护不再运行，需手动执行磁盘优化和安全扫描"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance", "MaintenanceDisabled", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_storage_sense",
            title="禁用存储感知",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["阻止存储感知自动清理临时文件和回收站"],
            side_effects=["存储感知不再自动清理磁盘，需手动管理磁盘空间"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\StorageSense", "AllowStorageSenseGlobal", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_reserved_storage",
            title="禁用更新保留存储",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["释放约 7GB 的更新保留磁盘空间"],
            side_effects=["Windows 更新可能因空间不足而失败"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ReserveManager", "ShippedWithReserves", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_experimentation",
            title="禁用 Windows A/B 实验",
            category="system",
            preset="safe",
            risk="green",
            evidence="high",
            benefit=["阻止微软在你的设备上运行 A/B 功能实验"],
            side_effects=["不再参与 Windows 新功能的灰度测试"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\PolicyManager\current\device\System", "AllowExperimentation", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\System\AllowExperimentation", "value", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_wudf_logging",
            title="禁用 WUDF 驱动框架日志",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["减少 Windows User Mode Driver Framework 日志开销"],
            side_effects=["驱动框架日志不再记录，排查驱动问题时缺少日志"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF", "LogEnable", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\WUDF", "LogLevel", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_coalescing_timer",
            title="禁用系统定时器合并",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用 CoalescingTimerInterval 减少定时器合并带来的延迟抖动"],
            side_effects=["定时器不再合并，可能略微增加中断频率"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager", "CoalescingTimerInterval", 0, "dword"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Executive", "CoalescingTimerInterval", 0, "dword", qualifier="exec"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel", "CoalescingTimerInterval", 0, "dword", qualifier="kern"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management", "CoalescingTimerInterval", 0, "dword", qualifier="mem"),
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\Power", "CoalescingTimerInterval", 0, "dword", qualifier="power"),
            ],
        ),
        Optimization(
            id="disable_fg_boost_decay",
            title="保持前台进程 Boost 不衰减",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["DisableFGBoostDecay 阻止前台提升优先级自动衰减"],
            side_effects=["后台进程可能得不到及时调度"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SYSTEM\CurrentControlSet\Control\KernelVelocity", "DisableFGBoostDecay", 1, "dword"),
            ],
        ),
        Optimization(
            id="ifeo_boost_critical",
            title="IFEO 提升关键进程优先级",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["dwm 设高优先级、audiodg 设高于正常，减少渲染和音频延迟"],
            side_effects=["关键进程占用更多 CPU 时间片"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\dwm.exe\\PerfOptions", "CpuPriorityClass", 4, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\dwm.exe\\PerfOptions", "IoPriority", 3, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\audiodg.exe\\PerfOptions", "CpuPriorityClass", 2, "dword"),
            ],
        ),
        # ── IFEO deprioritization: svchost.exe and TrustedInstaller.exe are blocked ──
        Optimization(
            id="ifeo_deprioritize_services",
            title="IFEO 降低后台服务优先级",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["wuauclt / SearchIndexer 设低于正常优先级，减少对前台干扰"],
            side_effects=["Windows Update 下载和索引速度可能降低"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\wuauclt.exe\\PerfOptions", "CpuPriorityClass", 1, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\wuauclt.exe\\PerfOptions", "IoPriority", 0, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\SearchIndexer.exe\\PerfOptions", "CpuPriorityClass", 1, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\SearchIndexer.exe\\PerfOptions", "IoPriority", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_fth",
            title="禁用故障容错堆 (FTH)",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["禁用 FTH 避免系统自动降低频繁崩溃程序的性能参数"],
            side_effects=["频繁崩溃的程序不再被自动降级保护，可能反复崩溃"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\FTH", "Enabled", 0, "dword"),
            ],
        ),
        Optimization(
            id="ifeo_extend_critical",
            title="IFEO 扩展关键进程优先级",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["fontdrvhost/sihost/lsass 设低优先级，减少对前台进程干扰"],
            side_effects=["系统关键进程优先级降低，极端情况下可能影响系统响应"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\fontdrvhost.exe\\PerfOptions", "CpuPriorityClass", 1, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\fontdrvhost.exe\\PerfOptions", "IoPriority", 0, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\sihost.exe\\PerfOptions", "CpuPriorityClass", 1, "dword"),
                RegistrySetAction("HKLM", f"{IFEO_BASE}\\lsass.exe\\PerfOptions", "CpuPriorityClass", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_visual_effects",
            title="优化视觉效果为性能优先",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["关闭动画、阴影、淡入淡出等视觉效果，减少 GPU 和 CPU 开销"],
            side_effects=["界面视觉效果降低，失去动画和平滑过渡"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects", "VisualFXSetting", 2, "dword", qualifier="vfx2"),
                RegistrySetAction("HKCU", r"Control Panel\Desktop", "DragFullWindows", "0", "sz"),
                RegistrySetAction("HKCU", r"Control Panel\Desktop\WindowMetrics", "MinAnimate", "0", "sz", qualifier="vfx2"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "ListviewAlphaSelect", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarAnimations", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_consumer_features",
            title="禁用 Windows 消费者功能和提示",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["禁用开始菜单应用推荐、锁屏提示和 Windows 消费者体验"],
            side_effects=["开始菜单不再推荐应用，Windows 技巧和提示不显示"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338389Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-310093Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338388Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-314559Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-338393Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353694Enabled", 0, "dword"),
                RegistrySetAction("HKCU", r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager", "SubscribedContent-353696Enabled", 0, "dword"),
            ],
        ),
        Optimization(
            id="disable_error_reporting",
            title="禁用 Windows 错误报告策略",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["通过组策略禁用错误报告，停止崩溃数据上传"],
            side_effects=["应用崩溃时不再自动上传错误报告"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting", "Disabled", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting", "DontSendAdditionalData", 1, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting", "LoggingDisabled", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_handwriting_error",
            title="禁用手写识别错误报告",
            category="system",
            preset="safe",
            risk="green",
            evidence="medium",
            benefit=["阻止手写识别错误数据上传"],
            side_effects=["手写识别错误不再上报"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports", "PreventHandwritingErrorReports", 1, "dword"),
            ],
        ),
        Optimization(
            id="disable_app_compat_prefer",
            title="禁用应用程序兼容性引擎",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="medium",
            benefit=["跳过兼容性引擎检查加快应用启动"],
            side_effects=["旧应用兼容性自动修复不再生效"],
            legacy_ids=[],
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "DisableEngine", 1, "dword", qualifier="compat2"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "SbEnable", 0, "dword"),
                RegistrySetAction("HKLM", r"SOFTWARE\Policies\Microsoft\Windows\AppCompat", "DisableUAR", 1, "dword", qualifier="compat2"),
            ],
        ),
        Optimization(
            id="disable_mpo",
            title="禁用 Multiplane Overlay (MPO)",
            category="system",
            preset="aggressive",
            risk="yellow",
            evidence="low",
            benefit=["禁用 MPO 减少帧合成延迟，部分显卡驱动兼容性改善"],
            side_effects=["禁用 MPO 后 DWM 使用传统合成路径，多显示器场景可能有差异"],
            legacy_ids=[],
            requires_admin=True,
            actions=[
                RegistrySetAction("HKLM", r"SOFTWARE\Microsoft\Windows\Dwm", "OverlayTestMode", 0, "dword"),
            ],
        ),
    ]
